### ISSUE TITLE
Tsavorite.test fails to compile on main: TestBase.cs references Garnet.test.TestUtils, which is not linked into Tsavorite.test.csproj

### ISSUE THREAD

**Issue by TedHartMS** [microsoft/garnet#2161]
### Describe the bug

`Tsavorite.test.csproj` does not compile on current `main` (`5c6e59536`). All four `Build Tsavorite` CI jobs (ubuntu/windows × Debug/Release) fail with:

```
TestBase.cs(46,9): error CS0234: The type or namespace name 'TestUtils'
  does not exist in the namespace 'Garnet.test'  [Tsavorite.test.csproj]
```

**Cause.** `libs/storage/Tsavorite/cs/test/Tsavorite.test.csproj:14` links exactly one file out of Garnet.test:

```xml
<Compile Include="..\..\..\..\..\test\standalone\Garnet.test\TestBase.cs" Link="TestBase.cs" />
```

`TestUtils.cs` is not linked. #2151 ("Give tests per-checkout port isolation via `GARNET_TEST_PORT_SLOT`") added a call to it inside `TestBase.cs`:

```csharp
[OneTimeSetUp]
public void Install()
{
    // Resolve the port slot before any test runs. ...
    Garnet.test.TestUtils.EnsurePortSlotResolved();   // TestBase.cs:46
```

Any project linking `TestBase.cs` now also needs `TestUtils.cs`. `Tsavorite.test` does not have it.

This also blocks unrelated PRs, which inherit the failure as soon as their branch is updated to current `main` (e.g. #2147).

### Steps to reproduce the bug

```
git checkout 5c6e59536      # pristine main
dotnet build libs\storage\Tsavorite\cs\test\Tsavorite.test.csproj -c Debug -f net10.0
```

Fails with the `CS0234` above, on an otherwise untouched checkout.

### Expected behavior

`Tsavorite.test` builds on `main`.

### Suggested fix

I tested both candidates rather than guessing.

**Linking `TestUtils.cs` alongside `TestBase.cs` does not work** — 122 errors:

```
error CS0234: The type or namespace name 'client' does not exist in the namespace 'Garnet'
error CS0234: The type or namespace name 'common' does not exist in the namespace 'Garnet'
error CS0234: The type or namespace name 'server' does not exist in the namespace 'Garnet'
error CS0234: The type or namespace name 'CSharp' does not exist in the namespace 'Microsoft.CodeAnalysis'
```

`TestUtils.cs` needs `Garnet.client`, `Garnet.common`, `Garnet.server`, `Garnet.server.Auth.Settings`, `Garnet.server.TLS`, Roslyn and `StackExchange.Redis`, whereas `Tsavorite.test` references only `Tsavorite.core` and `Tsavorite.devices.AzureStorageDevice`. Satisfying it would give the storage engine's test project a dependency on the Garnet server stack, inverting the layering.

**Guarding the single Garnet-only line works**, and is validated:

```csharp
// TestBase.cs
#if !TSAVORITE_TEST
        Garnet.test.TestUtils.EnsurePortSlotResolved();
#endif
```

```xml
<!-- Tsavorite.test.csproj, inside a PropertyGroup (it is a property, not an item) -->
<DefineConstants>$(DefineConstants);TSAVORITE_TEST</DefineConstants>
```

| project | build |
|---|---|
| `Tsavorite.test` | exit 0 |
| `Garnet.test` | exit 0 |
| `Garnet.test.cluster` | exit 0 |

This is semantically correct and not merely a compile workaround: `Tsavorite.test` references neither Garnet.server nor Garnet's `TestUtils`, so it never binds Garnet's per-sub-project test ports and has no port slot to claim. The symbol stays undefined in `Garnet.test` and `Garnet.test.cluster`, so #2151's isolation is unaffected there.

A cleaner structural alternative, if maintainers prefer avoiding `#if`: move the `GlobalUnhandledExceptionHandling` `[SetUpFixture]` out of `TestBase.cs` into its own file in Garnet.test. `Tsavorite.test` links only `TestBase.cs`, so it would stop seeing the Garnet-only call — at the cost of losing the unhandled-exception diagnostics it currently inherits incidentally.

### Release version

`main` @ `5c6e59536`

### OS version

Reproduced locally on Windows (net10.0); CI fails on both ubuntu-latest and windows-latest, Debug and Release.

### Additional context

Introduced by #2151. Found while analyzing CI on #2147, which is not otherwise implicated — it touches neither `TestBase.cs` nor `Tsavorite.test.csproj`.

**Comment by TedHartMS** [comment]
Confirming this independently from a third PR (#2139), and adding one finding that widens the blast radius beyond what the issue currently describes.

### The break is not confined to the four `Build Tsavorite` jobs — it takes out the entire Tsavorite test matrix

`Tsavorite.test.csproj` is not a leaf. Every one of the seven Tsavorite sub-test projects `ProjectReference`s it:

```
libs/storage/Tsavorite/cs/test/test.epoch/Tsavorite.test.epoch.csproj
libs/storage/Tsavorite/cs/test/test.hlog/Tsavorite.test.hlog.csproj
libs/storage/Tsavorite/cs/test/test.recordops/Tsavorite.test.recordops.csproj
libs/storage/Tsavorite/cs/test/test.recovery/Tsavorite.test.recovery.csproj
libs/storage/Tsavorite/cs/test/test.session/Tsavorite.test.session.csproj
libs/storage/Tsavorite/cs/test/test.session.context/Tsavorite.test.session.context.csproj
libs/storage/Tsavorite/cs/test/test.stress/Tsavorite.test.stress.csproj
```

So the `CS0234` propagates transitively. Building any sub-project on its own fails, even though it neither links `TestBase.cs` nor touches the port-slot code:

```
$ dotnet build libs/storage/Tsavorite/cs/test/test.epoch/Tsavorite.test.epoch.csproj -c Debug -f net10.0
TestBase.cs(46,9): error CS0234: The type or namespace name 'TestUtils'
  does not exist in the namespace 'Garnet.test'  [Tsavorite.test.csproj::TargetFramework=net10.0]
Build FAILED.   (exit 1)
```

The error is *attributed* to `Tsavorite.test.csproj`, which is what makes this easy to miss — the failing build is the sub-project's, and its own sources are fine.

### Why that matters for reading CI

`ci.yml`'s `test-tsavorite` job declares `needs: [changes, build-tsavorite]` (`ci.yml:217`), and its matrix is `2 os × 2 framework × 2 configuration × 7 test projects` (`ci.yml:222-225`) = 56 jobs. Because the dependency fails, those **56 jobs are skipped rather than failed**. On the PR checks page that renders as absent, not red, so the four red `Build Tsavorite` jobs understate the impact: *no Tsavorite test coverage runs at all* while this is broken. `nightly.yml` is in the same position — it builds the same `Tsavorite.slnx` (`nightly.yml:116`) and matrixes the same seven projects, with `Tsavorite.test.stress` in place of `Tsavorite.test.epoch` (`nightly.yml:84`), and `test.stress` references `Tsavorite.test` too.

### Independent validation of the guard fix

I hit this on #2139 (a `LightEpoch` change, which touches neither `TestBase.cs` nor `Tsavorite.test.csproj`) after merging current `main`. Before finding this issue I arrived independently at the same fix proposed above — `#if !TSAVORITE_TEST` around the single call, plus `<DefineConstants>$(DefineConstants);TSAVORITE_TEST</DefineConstants>` in a `PropertyGroup` — and it builds clean and unblocks the dependent projects: with it applied locally, `Tsavorite.test.epoch` ran **18/18 passing**. I then reverted it, since the fix belongs here rather than buried in an unrelated PR. Two sessions converging on the same one-line guard from different starting points is reasonable signal that it is the right minimal fix.

I'd add one point in favour of the guard over the "move `GlobalUnhandledExceptionHandling` to its own file" alternative: the guard keeps the unhandled-exception diagnostics that `Tsavorite.test` currently inherits from `TestBase.cs`. Moving the `[SetUpFixture]` out would silently drop them for the storage-engine tests, which is a real (if small) loss of diagnostics in exactly the projects most likely to fail in hard-to-attribute ways.

### Repro is not branch-specific

Reproduced on this worktree at `main`'s `5c6e59536` merged in, on Windows / net8.0 and net10.0, matching the report. No behavioural change of mine is involved — #2139's own tests pass once the guard is applied.

**Comment by TedHartMS** [comment]
## Update: a third option, tested — and it's the better one

@tedhar (session `tedhar-fix-devicelogcommit-shared-io-completion`) proposed a third approach, and I held it to the same bar as the other two: I built and ran it rather than reasoning about it. **It works, needs no conditional compilation, and matches a pattern this repo already uses everywhere else.** I'd recommend it over the `#if` option I originally wrote up.

### The framing that makes it click

The root problem is that **shared** source (`TestBase.cs`, linked into three projects) acquired a dependency on **non-shared** source (`TestUtils.cs`, present in only two). The `#if` resolves that by forking the shared file per consumer — it compiles, but it leaves shared test infrastructure carrying a project-specific switch that the next person linking `TestBase.cs` has to know about.

Removing the dependency at the root is cleaner: drop the call from `TestBase.Install()` and put it in a `[SetUpFixture]` in the assemblies that actually own `TestUtils`.

### This is already the repo's own convention

`TestUtils.cs:195` documents it explicitly:

> `/// Call from a <c>[SetUpFixture]</c> in each sub-project.`

And **19 sub-projects already do exactly that** — `Garnet.test.collections`, `.acl`, `.extensions`, `.scripting`, `.rangeindex`, `.vectorset`, `.complexstring`, every `Garnet.test.cluster.*`, and more each have a `TestProjectSetup.cs`. `Garnet.test` and `Garnet.test.cluster` are the only two that lack one, which is precisely why #2151 had to reach into `TestBase.cs` instead. So this option doesn't invent a pattern — it finishes applying the existing one.

### The change

Delete the 4 lines from `TestBase.cs` (the call plus its comment), and add one file per project, mirroring the existing `TestProjectSetup.cs` files:

```csharp
// test/standalone/Garnet.test/TestProjectSetup.cs
namespace Garnet.test
{
    [SetUpFixture]
    public class TestProjectSetup
    {
        [OneTimeSetUp]
        public void SetPort() => TestUtils.EnsurePortSlotResolved();
    }
}
```

...and the same for `test/cluster/Garnet.test.cluster/TestProjectSetup.cs` (class named `ClusterTestProjectSetup` there). Net diff: **`TestBase.cs` loses 4 lines and gains nothing**; no `.csproj` edits at all.

### Validation

Builds, on pristine `main` @ `5c6e59536`:

| project | build |
|---|---|
| `Tsavorite.test` | ✅ exit 0, 0 errors |
| `Garnet.test` | ✅ exit 0, 0 errors |
| `Garnet.test.cluster` | ✅ exit 0, 0 errors |

Runtime — `Garnet.test` `PortSlotTests`: **18/18 passed**. `Garnet.test.cluster` `ClusterConfigTests`: **16/16 passed**.

Crucially, the eager-failure property #2151 was built for is preserved. With `GARNET_TEST_PORT_SLOT=99` (invalid), both assemblies fail at `OneTimeSetUp` with the actionable message, not lazily mid-test:

```
Garnet.test:
  OneTimeSetUp: SetUp : System.InvalidOperationException :
    GARNET_TEST_PORT_SLOT must be 'auto' or an integer in [0, 7]; got '99'.
  at Garnet.test.TestProjectSetup.SetPort()

Garnet.test.cluster:
  OneTimeSetUp: SetUp : System.InvalidOperationException :
    GARNET_TEST_PORT_SLOT must be 'auto' or an integer in [0, 7]; got '99'.
  at Garnet.test.ClusterTestProjectSetup.SetPort()
```

The `TypeInitializationException` unwrapping in `EnsurePortSlotResolved` still produces the actionable message rather than "the type initializer threw an exception".

### Two things I checked because they could have sunk it

**1. Namespace coverage.** An NUnit `SetUpFixture` covers its own namespace and nested ones — so a `Garnet.test` fixture does *not* cover a parent namespace (`Garnet`) or an unrelated top-level one (`GarnetClusterManagement`). Both assemblies do have types in those namespaces: `DeleteTxn.cs`, `TestProcedureBitmap.cs` and 8 others under `namespace Garnet`, and `ClientClusterConfig.cs` under `namespace GarnetClusterManagement`. I checked each — **none contains a `[Test]`, `[TestCase]` or `[TestFixture]`**; they're transaction/procedure helpers and a config helper. So every actual test in both assemblies is covered. The cluster run above confirms it empirically: tests in `Garnet.test.cluster` (nested under `Garnet.test`) do trigger the fixture.

This is worth stating in the fix if it's taken, because it's the one way this could silently rot: a future test placed in `namespace Garnet` or `GarnetClusterManagement` would not get eager slot resolution.

**2. Duplicate-fixture collision.** `TestBase.cs` already contains a namespace-less `[SetUpFixture]` (`GlobalUnhandledExceptionHandling`), and NUnit allows only one per namespace. The new fixtures are in `Garnet.test`, not global, so there's no conflict — confirmed by the passing runs. The cluster sub-projects' own global `TestProjectSetup` classes are also safe: they consume `Garnet.test.cluster` via `ProjectReference`, not `<Compile Include>`, and NUnit discovers fixtures only in the assembly under test.

### Recommendation

Option 3 over option 2. It fixes the build, leaves `TestBase.cs` dependency-clean and free of compile switches, and converges the last two projects onto the pattern the other 19 already follow. Option 2 (`#if TSAVORITE_TEST`) remains valid and validated if a smaller, more surgical diff is preferred.

Credit to @tedhar for the design; the testing here is just me applying the standard he rightly held me to.

**Comment by TedHartMS** [comment]
Noting for the record, since this is now closed: the compile break itself was fixed by #2159 (`3df8b93da`), which gated the call behind a `GARNET_TEST_UTILS` symbol defined by the two projects that compile `TestUtils.cs`. That is option 2 at opposite polarity — opt **in** for the Garnet test projects rather than opt **out** for Tsavorite — and it is arguably the better default, since a future project that link-compiles `TestBase.cs` gets the call excluded automatically instead of having to remember to define an exclusion symbol.

One part of this is **not** resolved, and is worth separating from the compile error: the CI gap that let the break reach `main` in the first place.

#2159's own commit message diagnoses it exactly:

> CI did not catch this because the tsavorite path filter in ci.yml only watches `'libs/storage/Tsavorite/**'`, and #2151 touched only `test/**` and `.github/**`, so every Tsavorite job was skipped.

That diagnosis is right, but no workflow file was changed, so the filter on `main` today is still:

```yaml
tsavorite:
  - 'libs/storage/Tsavorite/**'
```

`TestBase.cs` is the only item in any `.csproj` under `libs/storage/Tsavorite/` that reaches outside the Tsavorite tree, so an edit confined to it still runs **zero** Tsavorite jobs. And because `test-tsavorite` is `needs: build-tsavorite`, its 56-job matrix is *skipped* rather than failed — which renders as absent on the checks page, not red. That combination is what made #2151 look clean.

#2162 carries a filter change for this (scoped to the single linked file rather than the whole `Garnet.test` directory, to avoid firing 60 Tsavorite jobs on unrelated edits). It is self-demonstrating: that PR touches nothing under `libs/storage/Tsavorite/**`, and all 61 Tsavorite jobs ran and passed on it, where the current filter would have skipped every one.

Flagging rather than reopening — the compile error this issue reports is genuinely fixed.
